filter:
    excluded_paths: [tests/*]
checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
tools:
    external_code_coverage:
        timeout: 600
        runs: 3
    php_analyzer: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: ['src']
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
build:
  environment:
    php:
      version: '7.0'
      ini:
        'date.timezone': 'Europe/Moscow'
  dependencies:
    before:
      - composer self-update && composer --version
      - composer global require "fxp/composer-asset-plugin:~1.3"
      - export PATH="$HOME/.composer/vendor/bin:$PATH"
      - composer install --dev --prefer-dist --no-interaction
      - composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
      - pear config-set preferred_state beta
      - pecl channel-update pecl.php.net
      - yes | pecl install imagick
      - php -m
      - cd tests; codecept build; cd ..
      - chmod -R 0777 tests/runtime
      - chmod -R 0777 tests/web/assets
  tests:
      override:
        -
          command: cd tests; codecept run --coverage --coverage-xml; cd ../
          coverage:
            file: tests/codeception/_output/coverage.xml
            format: php-clover